import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Bookmark, Check, List, X } from "lucide-react";
import type { ReaderChapter } from "./types";

type BookmarkItem = { id: number; pageNumber: number; label: string | null };

export function ContentsDrawer({ open, onOpenChange, bookTitle, chapters, currentChapter, currentPage, bookmarks, onGoToPage }: { open: boolean; onOpenChange: (open: boolean) => void; bookTitle: string; chapters: ReaderChapter[]; currentChapter?: number; currentPage: number; bookmarks: BookmarkItem[]; onGoToPage: (page: number) => void }) {
  const go = (page: number) => { onGoToPage(page); onOpenChange(false); };
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetTrigger asChild><button className="hidden h-8 items-center gap-1.5 rounded-md px-2.5 text-[11px] font-medium text-muted-foreground transition-colors hover:bg-[#8a85c9]/10 hover:text-[#6f6ab2] sm:flex" aria-label="Open contents"><List className="h-3.5 w-3.5" /> Contents</button></SheetTrigger><SheetContent side="left" className="w-[340px] border-r border-[#8a85c9]/15 bg-[#fcfaf5] p-0 sm:max-w-[340px]"><SheetHeader className="border-b border-[#8a85c9]/12 px-6 pb-5 pt-7 text-left"><SheetTitle className="font-display text-2xl font-semibold leading-tight">{bookTitle}</SheetTitle><p className="mt-1 text-xs text-muted-foreground">Page {currentPage}</p></SheetHeader><div className="h-[calc(100vh-120px)] overflow-y-auto px-4 py-5"><p className="mb-3 px-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#6f6ab2]">Contents</p>{chapters.length > 0 ? <div className="space-y-1">{chapters.map(chapter => { const complete = chapter.startPage < currentPage && chapter.chapter !== currentChapter; const active = chapter.chapter === currentChapter; return <button key={chapter.chapter} onClick={() => go(chapter.startPage)} className={`flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left transition-colors ${active ? "bg-[#8a85c9]/10 text-[#5f5aa0]" : "hover:bg-[#8a85c9]/[0.06]"}`}><span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center">{complete ? <Check className="h-3.5 w-3.5 text-[#6f6ab2]" /> : active ? <span className="h-2 w-2 rounded-full bg-[#6f6ab2]" /> : null}</span><span><span className="block text-sm font-medium">{chapter.title || `Chapter ${chapter.chapter}`}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">p. {chapter.startPage}</span></span></button>; })}</div> : <p className="px-2 text-sm leading-relaxed text-muted-foreground">Contents will appear as this book finishes processing.</p>}{bookmarks.length > 0 && <><div className="my-6 border-t border-[#8a85c9]/12" /><p className="mb-3 flex items-center gap-2 px-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#6f6ab2]"><Bookmark className="h-3 w-3" /> Bookmarks</p><div className="space-y-1">{bookmarks.map(bookmark => <button key={bookmark.id} onClick={() => go(bookmark.pageNumber)} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left hover:bg-[#8a85c9]/[0.06]"><span className="truncate text-sm">{bookmark.label || `Page ${bookmark.pageNumber}`}</span><span className="ml-4 shrink-0 text-[11px] text-muted-foreground">p. {bookmark.pageNumber}</span></button>)}</div></>}</div></SheetContent></Sheet>;
}

