import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Slider } from "@/components/ui/slider";
import { Moon, Palette, Settings2, Sun } from "lucide-react";
import type { ReadingTheme } from "./types";

const fontSizes = [16, 17, 18, 19, 20, 22, 24];
const widths = ["Narrow", "Comfortable", "Wide"];
const lineLabels = ["Tight", "Normal", "Relaxed", "Spacious"];

export function ReaderSettings({ fontSizeIndex, setFontSizeIndex, widthIndex, setWidthIndex, lineHeightIndex, setLineHeightIndex, theme, setTheme, continuousMode, setContinuousMode }: { fontSizeIndex: number; setFontSizeIndex: (value: number) => void; widthIndex: number; setWidthIndex: (value: number) => void; lineHeightIndex: number; setLineHeightIndex: (value: number) => void; theme: ReadingTheme; setTheme: (theme: ReadingTheme) => void; continuousMode: boolean; setContinuousMode: (value: boolean) => void }) {
  return <Popover><PopoverTrigger asChild><Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:bg-[#8a85c9]/10 hover:text-[#6f6ab2]" aria-label="Reading settings"><Settings2 className="h-4 w-4" /></Button></PopoverTrigger><PopoverContent align="end" className="w-72 border-[#8a85c9]/15 p-4 shadow-lift"><div className="space-y-5"><div><p className="mb-2 text-xs font-semibold">Appearance</p><div className="grid grid-cols-3 gap-1.5">{(["light", "sepia", "dark"] as ReadingTheme[]).map(value => <Button key={value} variant={theme === value ? "default" : "outline"} size="sm" onClick={() => setTheme(value)} className={`h-8 text-[11px] ${theme === value ? "bg-[#6f6ab2] hover:bg-[#5f5aa0]" : "border-[#8a85c9]/15 hover:bg-[#8a85c9]/[0.06]"}`}>{value === "light" ? <Sun className="mr-1 h-3 w-3" /> : value === "dark" ? <Moon className="mr-1 h-3 w-3" /> : <Palette className="mr-1 h-3 w-3" />}{value === "light" ? "Paper" : value === "sepia" ? "Sepia" : "Night"}</Button>)}</div></div><div><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold">Text size</p><span className="text-[11px] text-muted-foreground">{fontSizes[fontSizeIndex]}px</span></div><Slider value={[fontSizeIndex]} min={0} max={fontSizes.length - 1} step={1} onValueChange={value => setFontSizeIndex(value[0] ?? 1)} /></div><div><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold">Line spacing</p><span className="text-[11px] text-muted-foreground">{lineLabels[lineHeightIndex]}</span></div><Slider value={[lineHeightIndex]} min={0} max={lineLabels.length - 1} step={1} onValueChange={value => setLineHeightIndex(value[0] ?? 2)} /></div><div><p className="mb-2 text-xs font-semibold">Reading width</p><div className="grid grid-cols-3 gap-1.5">{widths.map((label, index) => <Button key={label} variant={widthIndex === index ? "default" : "outline"} size="sm" onClick={() => setWidthIndex(index)} className={`h-8 text-[11px] ${widthIndex === index ? "bg-[#6f6ab2] hover:bg-[#5f5aa0]" : "border-[#8a85c9]/15 hover:bg-[#8a85c9]/[0.06]"}`}>{label}</Button>)}</div></div><div className="flex items-center justify-between rounded-xl bg-[#8a85c9]/[0.055] px-3 py-3"><div><p className="text-xs font-semibold">Continuous reading</p><p className="mt-0.5 text-[10px] text-muted-foreground">Keep the next page flowing below.</p></div><button type="button" role="switch" aria-checked={continuousMode} onClick={() => setContinuousMode(!continuousMode)} className={`relative h-5 w-9 rounded-full transition-colors ${continuousMode ? "bg-[#6f6ab2]" : "bg-muted"}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition-transform ${continuousMode ? "translate-x-4" : "translate-x-0.5"}`} /></button></div></div></PopoverContent></Popover>;
}

