import { BookOpen, Mail, ArrowRight } from "lucide-react";
import { Link, useLocation } from "wouter";
import { FormEvent, useState } from "react";
import { trpc } from "@/lib/trpc";

export default function AuthPage({ create = false }: { create?: boolean }) {
  const [, navigate] = useLocation(); const [email, setEmail] = useState(""); const [sent, setSent] = useState(false);
  const magic = trpc.auth.requestEmailLink.useMutation({ onSuccess: () => setSent(true) });
  const submit = (event: FormEvent) => { event.preventDefault(); magic.mutate({ email, origin: window.location.origin }); };
  const google = () => { window.location.assign(`/api/auth/google/start?origin=${encodeURIComponent(window.location.origin)}`); };
  const title = create ? "Begin your reading life." : "Welcome back.";
  return <main className="min-h-screen bg-[radial-gradient(circle_at_15%_10%,#efe9ff,transparent_32%),#fbf8f0] px-5 py-6 text-[#101c3d]">
    <div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-5xl overflow-hidden rounded-[2rem] border border-[#ddd6c8] bg-[#fffdf8] shadow-[0_24px_80px_rgba(16,28,61,.12)]">
      <section className="hidden w-[43%] flex-col justify-between bg-[#101c3d] p-10 text-[#fbf8f0] md:flex"><div className="flex items-center gap-2 font-display text-xl"><span className="text-[#8b78ff]">↯</span> ReadBuddy</div><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.18em] text-[#b5aaff]">Your reading, remembered</p><h1 className="font-display text-5xl leading-[.98]">A quieter place to understand what you read.</h1></div><p className="max-w-xs text-sm leading-6 text-[#c7cfdf]">Your books, highlights, and explanations remain personal to your account.</p></section>
      <section className="flex flex-1 items-center justify-center p-6 sm:p-12"><div className="w-full max-w-sm"><Link href="/" className="mb-10 inline-flex items-center gap-2 font-display text-lg md:hidden"><BookOpen className="h-5 w-5 text-[#7665ec]"/>ReadBuddy</Link><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#7665ec]">{create ? "Create account" : "Sign in"}</p><h2 className="mt-3 font-display text-4xl leading-none">{title}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{create ? "Use Google or your email. No password needed." : "Continue where you left off, with your books and notes ready."}</p>
        <button onClick={google} className="mt-8 flex h-12 w-full items-center justify-center gap-3 rounded-xl border border-[#d8d1c5] bg-white text-sm font-semibold shadow-sm transition hover:bg-[#f7f4ee]"><span className="grid h-5 w-5 place-items-center rounded-full bg-[#4285f4] text-[11px] text-white">G</span>Continue with Google</button>
        <div className="my-6 flex items-center gap-3 text-xs text-muted-foreground before:h-px before:flex-1 before:bg-border after:h-px after:flex-1 after:bg-border">or</div>
        {sent ? <div className="rounded-xl border border-[#c8c1ff] bg-[#f4f1ff] p-4 text-sm leading-6">Check <strong>{email}</strong> for a one-time ReadBuddy sign-in link. It expires in 15 minutes.</div> : <form onSubmit={submit} className="space-y-3"><label className="text-sm font-medium">Email address</label><div className="relative"><Mail className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={email} onChange={e => setEmail(e.target.value)} required type="email" placeholder="you@example.com" className="h-11 w-full rounded-xl border border-input bg-background pl-10 pr-3 text-sm outline-none focus:border-[#7665ec] focus:ring-2 focus:ring-[#d8d1ff]"/></div><button disabled={magic.isPending} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#101c3d] text-sm font-semibold text-white transition hover:bg-[#1c2d5d] disabled:opacity-60">{magic.isPending ? "Sending link…" : "Email me a sign-in link"}<ArrowRight className="h-4 w-4"/></button>{magic.error && <p className="text-sm text-destructive">We could not send that link. Check the address and try again.</p>}</form>}
        <p className="mt-8 text-center text-sm text-muted-foreground">{create ? "Already have an account?" : "New to ReadBuddy?"} <button onClick={() => navigate(create ? "/login" : "/create-account")} className="font-semibold text-[#6353d9] underline underline-offset-4">{create ? "Log in" : "Create an account"}</button></p><p className="mt-6 text-center text-xs leading-5 text-muted-foreground">By continuing, you agree to use ReadBuddy responsibly. We never sell your reading data.</p></div></section>
    </div></main>;
}
