import { useMemo, useState } from "react";
import { BookOpen, Brain, FileText, Highlighter, Layers3, ListChecks, NotebookPen, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import AppShell from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { toast } from "sonner";

type Tab = "overview" | "read" | "learn" | "flashcards" | "quiz" | "notes";
const tabs: { id: Tab; label: string; icon: typeof BookOpen }[] = [{ id: "overview", label: "Overview", icon: Layers3 }, { id: "read", label: "Read", icon: BookOpen }, { id: "learn", label: "Learn", icon: Brain }, { id: "flashcards", label: "Flashcards", icon: Highlighter }, { id: "quiz", label: "Quiz", icon: ListChecks }, { id: "notes", label: "Notes", icon: NotebookPen }];

export default function MaterialWorkspace() {
  const [, params] = useRoute("/materials/:materialId");
  const materialId = Number(params?.materialId);
  const { isAuthenticated } = useAuth({ redirectOnUnauthenticated: true });
  const utils = trpc.useUtils();
  const [tab, setTab] = useState<Tab>("overview");
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const overview = trpc.materials.overview.useQuery({ materialId }, { enabled: isAuthenticated && Number.isFinite(materialId) });
  const units = trpc.materials.units.useQuery({ materialId }, { enabled: isAuthenticated && tab === "read" && Number.isFinite(materialId) });
  const saveNote = trpc.materials.saveNote.useMutation({ onSuccess: async () => { toast.success("Note saved."); setTitle(""); setContent(""); await utils.materials.overview.invalidate({ materialId }); }, onError: error => toast.error(error.message) });
  const [cardIndex, setCardIndex] = useState(0);
  const [showCardBack, setShowCardBack] = useState(false);
  const [quizFeedback, setQuizFeedback] = useState<Record<number, { isCorrect: boolean; explanation: string }>>({});
  const [lessonSession, setLessonSession] = useState<any>(null);
  const [lessonAnswer, setLessonAnswer] = useState("");
  const studySet = trpc.materials.studySet.useMutation({ onSuccess: async () => { toast.success("Grounded study set ready."); await Promise.all([utils.materials.flashcards.invalidate({ materialId }), utils.materials.quiz.invalidate({ materialId }), utils.materials.overview.invalidate({ materialId })]); }, onError: error => toast.error(error.message) });
  const flashcards = trpc.materials.flashcards.useQuery({ materialId }, { enabled: isAuthenticated && tab === "flashcards" });
  const quiz = trpc.materials.quiz.useQuery({ materialId }, { enabled: isAuthenticated && tab === "quiz" });
  const rateFlashcard = trpc.materials.rateFlashcard.useMutation({ onSuccess: async () => { setShowCardBack(false); setCardIndex(current => Math.min(current + 1, Math.max((flashcards.data?.length ?? 1) - 1, 0))); await flashcards.refetch(); }, onError: error => toast.error(error.message) });
  const answerQuestion = trpc.materials.answerQuizQuestion.useMutation({ onSuccess: (result, variables) => { setQuizFeedback(current => ({ ...current, [variables.questionId]: result })); }, onError: error => toast.error(error.message) });
  const lesson = trpc.materials.lesson.useMutation({ onSuccess: result => { setLessonSession(result); setLessonAnswer(""); }, onError: error => toast.error(error.message) });
  const completeLessonStep = trpc.materials.completeLessonStep.useMutation({ onSuccess: () => { setLessonAnswer(""); lesson.mutate({ materialId }); }, onError: error => toast.error(error.message) });
  const data = overview.data;
  const masteryByConcept = useMemo(() => new Map((data?.mastery ?? []).map(item => [item.conceptId, item.masteryState])), [data?.mastery]);
  if (overview.isLoading || !data) return <AppShell><div className="mx-auto max-w-6xl px-5 py-16 text-sm text-muted-foreground">Opening material workspace…</div></AppShell>;
  const { material, intelligence, concepts, notes } = data;
  return <AppShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12"><Link href="/materials" className="text-sm text-muted-foreground no-underline hover:text-foreground">← Materials</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Material workspace</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-[-.04em] sm:text-5xl">{material.title}</h1><p className="mt-3 text-sm text-muted-foreground">{material.unitCount} source units · {material.processingState === "complete" ? "Material Intelligence complete" : material.processingState === "paused" ? "Analysis paused safely" : "Preparing deeper understanding"}</p></div><div className="rounded-xl border border-border bg-card px-3 py-2 text-xs text-muted-foreground">{intelligence?.pipelineStage === "complete" ? "Grounded in your source" : "You can start learning now"}</div></div>
    <nav className="mt-8 flex gap-1 overflow-x-auto border-b border-border pb-px">{tabs.map(item => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-3 text-sm ${tab === item.id ? "border-primary text-foreground" : "border-transparent text-muted-foreground hover:text-foreground"}`}><item.icon className="h-3.5 w-3.5" />{item.label}</button>)}</nav>
    {tab === "overview" && <section className="mt-8 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-border bg-card p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">What this material is about</p><p className="mt-3 whitespace-pre-wrap leading-7 text-foreground">{intelligence?.overview ?? "ZhiyaAI is preparing a grounded overview from the source material."}</p>{(intelligence?.learningObjectives as string[] | null)?.length ? <><h2 className="mt-7 font-display text-xl">Learning objectives</h2><ul className="mt-3 space-y-2 text-sm text-muted-foreground">{(intelligence?.learningObjectives as string[]).map((objective, index) => <li key={index} className="flex gap-2"><span className="text-primary">•</span>{objective}</li>)}</ul></> : null}</div><aside className="rounded-2xl border border-border bg-primary/[.04] p-6"><Sparkles className="h-5 w-5 text-primary" /><h2 className="mt-4 font-display text-xl">What you can do now</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Read the original material, inspect concepts as they become ready, and keep source-linked notes. Flashcards, quizzes, and lessons appear here when they are generated from this material.</p></aside></section>}
    {tab === "read" && <section className="mt-8 space-y-4">{units.isLoading ? <p className="text-sm text-muted-foreground">Opening source…</p> : units.data?.map(unit => <article key={unit.id} className="rounded-2xl border border-border bg-card p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-primary">{unit.unitType} {unit.unitIndex}{unit.title ? ` · ${unit.title}` : ""}</p><p className="mt-3 whitespace-pre-wrap leading-7 text-foreground">{unit.content}</p></article>)}</section>}
    {tab === "learn" && <section className="mt-8"><h2 className="font-display text-2xl">Key concepts</h2><p className="mt-2 text-sm text-muted-foreground">Every definition is grounded in this material. Mastery becomes clearer as you work with it.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{concepts.length ? concepts.map(concept => <article key={concept.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex justify-between gap-3"><h3 className="font-display text-xl">{concept.canonicalName}</h3><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-bold uppercase text-primary">{masteryByConcept.get(concept.id) ?? "new"}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{concept.definition}</p><p className="mt-4 text-xs text-muted-foreground">Source: {(concept.evidence as { source?: { unitType?: string; unitIndex?: number } }[])?.[0]?.source?.unitType ?? "material"} {(concept.evidence as { source?: { unitIndex?: number } }[])?.[0]?.source?.unitIndex ?? ""}</p></article>) : <div className="rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">Concepts will appear after Material Intelligence finishes. Nothing is invented while it is processing.</div>}</div></section>}
    {tab === "learn" && <section className="mt-8 rounded-2xl border border-border bg-primary/[.035] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Personalized lesson</p><h2 className="mt-2 font-display text-2xl">Learn one idea at a time.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">A lesson starts with concepts that are new or need reinforcement. ZhiyaAI only records the learning signals you explicitly give it.</p></div>{!lessonSession && <Button disabled={lesson.isPending || !concepts.length} onClick={() => lesson.mutate({ materialId })}>Start a lesson</Button>}</div>{lessonSession && (() => { const step = lessonSession.steps.find((item: any) => !item.completedAt); if (!step) return <p className="mt-5 text-sm text-muted-foreground">This lesson is complete. Your next lesson will adapt to the signals you gave.</p>; const progress = `${lessonSession.steps.filter((item: any) => item.completedAt).length + 1} of ${lessonSession.steps.length}`; return <div className="mt-6 max-w-3xl rounded-2xl border border-border bg-card p-6"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-primary">{step.stepType}</span><span className="text-xs text-muted-foreground">{progress}</span></div><h3 className="mt-4 font-display text-2xl">{step.content}</h3>{step.checkPrompt && <><p className="mt-4 text-sm font-medium">{step.checkPrompt}</p><Textarea value={lessonAnswer} onChange={event => setLessonAnswer(event.target.value)} placeholder="Write a short explanation, if you want to." className="mt-3 min-h-24" /><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" disabled={completeLessonStep.isPending} onClick={() => completeLessonStep.mutate({ stepId: step.id, understood: false, learnerAnswer: lessonAnswer || undefined })}>I need it simpler</Button><Button disabled={completeLessonStep.isPending} onClick={() => completeLessonStep.mutate({ stepId: step.id, understood: true, learnerAnswer: lessonAnswer || undefined })}>I understand</Button></div></>}{!step.checkPrompt && <Button className="mt-5" disabled={completeLessonStep.isPending} onClick={() => completeLessonStep.mutate({ stepId: step.id })}>Continue</Button>}<p className="mt-5 text-xs text-muted-foreground">This step remains connected to the material source; it does not claim to grade an open response automatically.</p></div>; })()}</section>}
    {tab === "flashcards" && <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-display text-2xl">Flashcards</h2><p className="mt-2 text-sm text-muted-foreground">Each card is derived from a source-backed concept in this material.</p></div>{flashcards.data?.length ? <span className="text-sm text-muted-foreground">{Math.min(cardIndex + 1, flashcards.data.length)} of {flashcards.data.length}</span> : null}</div>{flashcards.isLoading ? <p className="mt-6 text-sm text-muted-foreground">Opening cards…</p> : !flashcards.data?.length ? <div className="mt-6 rounded-2xl border border-dashed border-border bg-card p-7"><p className="max-w-xl text-sm leading-6 text-muted-foreground">Create a compact first set of editable cards from the material’s verified concepts. ZhiyaAI will not make cards until source-backed concepts are ready.</p><Button className="mt-5" disabled={studySet.isPending} onClick={() => studySet.mutate({ materialId })}>Create grounded flashcards</Button></div> : (() => { const card = flashcards.data[Math.min(cardIndex, flashcards.data.length - 1)]; return <div className="mt-6 max-w-2xl"><button type="button" onClick={() => setShowCardBack(value => !value)} className="min-h-64 w-full rounded-3xl border border-border bg-card p-8 text-left transition hover:border-primary/35"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">{showCardBack ? "Answer" : "Prompt"}</p><p className="mt-5 font-display text-2xl leading-tight">{showCardBack ? card.back : card.front}</p><p className="mt-8 text-xs text-muted-foreground">Tap to {showCardBack ? "show prompt" : "reveal answer"} · Source evidence retained</p></button><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={() => rateFlashcard.mutate({ materialId, flashcardId: card.id, rating: "again" })}>Again</Button><Button variant="outline" onClick={() => rateFlashcard.mutate({ materialId, flashcardId: card.id, rating: "hard" })}>Hard</Button><Button onClick={() => rateFlashcard.mutate({ materialId, flashcardId: card.id, rating: "good" })}>Good</Button></div></div>; })()}</section>}
    {tab === "quiz" && <section className="mt-8"><h2 className="font-display text-2xl">Quiz</h2><p className="mt-2 text-sm text-muted-foreground">A conceptual check on ideas actually present in this material.</p>{quiz.isLoading ? <p className="mt-6 text-sm text-muted-foreground">Opening quiz…</p> : !quiz.data?.quiz ? <div className="mt-6 rounded-2xl border border-dashed border-border bg-card p-7"><p className="max-w-xl text-sm leading-6 text-muted-foreground">Create a focused source-grounded quiz. Answers update only the relevant concept’s learning signal.</p><Button className="mt-5" disabled={studySet.isPending} onClick={() => studySet.mutate({ materialId })}>Create conceptual quiz</Button></div> : <div className="mt-6 space-y-5">{quiz.data.questions.map((question, index) => { const feedback = quizFeedback[question.id]; return <article key={question.id} className="rounded-2xl border border-border bg-card p-6"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-primary">Question {index + 1}</p><h3 className="mt-3 font-display text-xl">{question.prompt}</h3><div className="mt-5 grid gap-2">{(question.choices ?? []).map(choice => <Button key={choice} variant="outline" disabled={Boolean(feedback) || answerQuestion.isPending} className="h-auto justify-start whitespace-normal py-3 text-left" onClick={() => answerQuestion.mutate({ questionId: question.id, selectedAnswer: choice })}>{choice}</Button>)}</div>{feedback && <div className={`mt-4 rounded-xl p-4 text-sm ${feedback.isCorrect ? "bg-emerald-500/10 text-emerald-800" : "bg-amber-500/10 text-amber-900"}`}><p className="font-medium">{feedback.isCorrect ? "Correct" : "Not quite"}</p><p className="mt-1 leading-6">{feedback.explanation}</p><p className="mt-2 text-xs opacity-75">Explanation is grounded in this material.</p></div>}</article>})}</div>}</section>}
    {tab === "notes" && <section className="mt-8 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><aside><h2 className="font-display text-2xl">Notes</h2><p className="mt-2 text-sm text-muted-foreground">Your notes stay attached to this material. Generated notes will show their source evidence.</p><div className="mt-5 space-y-3">{notes.map(note => <article key={note.id} className="rounded-xl border border-border bg-card p-4"><h3 className="font-medium">{note.title}</h3><p className="mt-1 line-clamp-3 text-sm text-muted-foreground">{note.content}</p></article>)}</div></aside><div className="rounded-2xl border border-border bg-card p-5"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Note title" /><Textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Write what you want to remember…" className="mt-3 min-h-48" /><Button className="mt-3" disabled={saveNote.isPending || !title.trim() || !content.trim()} onClick={() => saveNote.mutate({ materialId, title: title.trim(), content: content.trim() })}>Save note</Button></div></section>}
  </div></AppShell>;
}
