import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, Brain, CheckCircle2, Clock3, FileText, Highlighter, Layers3, ListChecks, NotebookPen, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import AppShell from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { toast } from "sonner";

type Tab = "overview" | "read" | "learn" | "flashcards" | "quiz" | "notes";
const tabs: { id: Tab; label: string; icon: typeof BookOpen }[] = [
  { id: "overview", label: "Overview", icon: Layers3 }, { id: "read", label: "Read", icon: BookOpen }, { id: "learn", label: "Learn", icon: Brain }, { id: "flashcards", label: "Flashcards", icon: Highlighter }, { id: "quiz", label: "Quiz", icon: ListChecks }, { id: "notes", label: "Notes", icon: NotebookPen },
];

function MaterialIntelligenceRetry({ materialId }: { materialId: number }) {
  const utils = trpc.useUtils();
  const retry = trpc.materials.retryIntelligence.useMutation({ onSuccess: async () => { toast.success("ZhiyaAI will resume understanding this material in the background."); await utils.materials.overview.invalidate({ materialId }); }, onError: error => toast.error(error.message) });
  return <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-300/55 bg-amber-50 px-5 py-4 text-sm text-amber-950"><span>Understanding paused safely. Your source and notes remain available.</span><Button size="sm" variant="outline" className="bg-white" disabled={retry.isPending} onClick={() => retry.mutate({ materialId })}>{retry.isPending ? "Retrying…" : "Retry understanding"}</Button></div>;
}

function Readiness({ state }: { state: string }) {
  const detail = state === "complete" ? { label: "Source understood", className: "bg-emerald-100 text-emerald-800" } : state === "paused" ? { label: "Needs attention", className: "bg-amber-100 text-amber-900" } : { label: "Understanding in progress", className: "bg-sky-100 text-sky-800" };
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.12em] ${detail.className}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{detail.label}</span>;
}

function EmptyStudyState({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="mt-6 rounded-[1.6rem] border border-dashed border-slate-300 bg-white/65 p-8 text-center sm:p-10"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-100 text-violet-700"><Sparkles className="h-5 w-5" /></div><h3 className="mt-5 font-display text-2xl tracking-[-.04em] text-slate-900">{title}</h3><div className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-600">{children}</div></div>;
}

export default function MaterialWorkspace() {
  const [, params] = useRoute("/materials/:materialId");
  const materialId = Number(params?.materialId);
  const { isAuthenticated } = useAuth({ redirectOnUnauthenticated: true });
  const utils = trpc.useUtils();
  const [tab, setTab] = useState<Tab>("overview");
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [cardIndex, setCardIndex] = useState(0);
  const [showCardBack, setShowCardBack] = useState(false);
  const [quizFeedback, setQuizFeedback] = useState<Record<number, { isCorrect: boolean; explanation: string }>>({});
  const overview = trpc.materials.overview.useQuery({ materialId }, { enabled: isAuthenticated && Number.isFinite(materialId) });
  const units = trpc.materials.units.useQuery({ materialId }, { enabled: isAuthenticated && tab === "read" && Number.isFinite(materialId) });
  const saveNote = trpc.materials.saveNote.useMutation({ onSuccess: async () => { toast.success("Note saved."); setTitle(""); setContent(""); await utils.materials.overview.invalidate({ materialId }); }, onError: error => toast.error(error.message) });
  const studySet = trpc.materials.studySet.useMutation({ onSuccess: async () => { toast.success("Grounded study set ready."); await Promise.all([utils.materials.flashcards.invalidate({ materialId }), utils.materials.quiz.invalidate({ materialId }), utils.materials.overview.invalidate({ materialId })]); }, onError: error => toast.error(error.message) });
  const flashcards = trpc.materials.flashcards.useQuery({ materialId }, { enabled: isAuthenticated && tab === "flashcards" });
  const quiz = trpc.materials.quiz.useQuery({ materialId }, { enabled: isAuthenticated && tab === "quiz" });
  const rateFlashcard = trpc.materials.rateFlashcard.useMutation({ onSuccess: async () => { setShowCardBack(false); setCardIndex(current => Math.min(current + 1, Math.max((flashcards.data?.length ?? 1) - 1, 0))); await flashcards.refetch(); }, onError: error => toast.error(error.message) });
  const answerQuestion = trpc.materials.answerQuizQuestion.useMutation({ onSuccess: (result, variables) => setQuizFeedback(current => ({ ...current, [variables.questionId]: result })), onError: error => toast.error(error.message) });
  const data = overview.data;
  const masteryByConcept = useMemo(() => new Map((data?.mastery ?? []).map(item => [item.conceptId, item.masteryState])), [data?.mastery]);
  if (overview.isError) return <AppShell><div className="mx-auto max-w-xl px-5 py-20 text-center sm:px-8"><div className="rounded-[1.8rem] border border-slate-200 bg-white p-8 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-500">Material unavailable</p><h1 className="mt-3 font-display text-3xl tracking-[-.05em] text-slate-950">This material is no longer available here.</h1><p className="mt-3 text-sm leading-6 text-slate-600">Return to your library and choose a material that is still in your account.</p><Link href="/materials" className="mt-6 inline-flex rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white no-underline">Back to materials</Link></div></div></AppShell>;
  if (overview.isLoading || !data) return <AppShell><div className="mx-auto max-w-6xl px-5 py-14 sm:px-8"><div className="h-4 w-28 animate-pulse rounded-full bg-slate-200" /><div className="mt-5 h-12 max-w-xl animate-pulse rounded-xl bg-slate-200" /><div className="mt-10 h-80 animate-pulse rounded-[2rem] bg-white" /></div></AppShell>;
  const { material, intelligence, concepts, notes } = data;
  const lessonLink = `/materials/${materialId}/lesson`;

  return <AppShell><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10">
    <Link href="/materials" className="inline-flex items-center gap-1 text-sm text-slate-500 no-underline transition hover:text-slate-900">← All materials</Link>
    <section className="mt-5 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-[0_20px_60px_rgba(36,61,98,.08)]"><div className="relative p-6 sm:p-8 md:p-10"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-sky-100/70 blur-3xl" /><div className="absolute -bottom-24 right-1/4 h-56 w-56 rounded-full bg-violet-100/60 blur-3xl" /><div className="relative flex flex-wrap items-start justify-between gap-5"><div className="min-w-0 max-w-3xl"><div className="flex flex-wrap items-center gap-3"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-700">Material workspace</p><Readiness state={material.processingState} /></div><h1 className="mt-4 break-words font-display text-4xl leading-[.98] tracking-[-.055em] text-slate-950 sm:text-5xl">{material.title}</h1><p className="mt-4 text-sm leading-6 text-slate-600">{material.unitCount} source unit{material.unitCount === 1 ? "" : "s"} · {intelligence?.pipelineStage === "complete" ? "Every learning artifact stays tied to this source." : "You can start learning while deeper understanding continues."}</p></div><div className="rounded-2xl border border-slate-200 bg-white/80 px-4 py-3 text-right backdrop-blur-sm"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Material map</p><p className="mt-1 font-display text-2xl text-slate-900">{concepts.length}</p><p className="text-xs text-slate-500">source-backed ideas</p></div></div></div></section>
    <nav aria-label="Material sections" className="mt-6 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">{tabs.map(item => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3.5 py-2.5 text-sm font-medium transition ${tab === item.id ? "bg-slate-900 text-white shadow-sm" : "text-slate-500 hover:bg-slate-100 hover:text-slate-900"}`}><item.icon className="h-3.5 w-3.5" />{item.label}</button>)}</nav>
    {intelligence?.pipelineStage === "paused" ? <MaterialIntelligenceRetry materialId={materialId} /> : null}

    {tab === "overview" ? <section className="mt-7 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="relative overflow-hidden rounded-[1.8rem] bg-slate-950 p-7 text-white sm:p-8"><div className="absolute -right-16 top-3 h-48 w-48 rounded-full bg-violet-500/30 blur-3xl" /><div className="relative"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em] text-violet-200"><Clock3 className="h-3.5 w-3.5" />About seven minutes</div><h2 className="mt-5 max-w-lg font-display text-3xl leading-[1.02] tracking-[-.05em] sm:text-4xl">Turn this material into an active revision session.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-slate-300">Notes, visual understanding, short checks, cards, and a recap—built only from the ideas ZhiyaAI found in your upload.</p>{concepts.length ? <Link href={lessonLink} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-950 no-underline transition hover:-translate-y-0.5">Start 7-minute lesson <ArrowRight className="h-4 w-4" /></Link> : <p className="mt-7 text-sm text-violet-200">The lesson unlocks as soon as source-backed ideas are ready.</p>}</div></article><article className="rounded-[1.8rem] border border-emerald-100 bg-emerald-50/65 p-7 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-800">What this material is about</p><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-emerald-950">{intelligence?.overview ?? "ZhiyaAI is preparing a grounded overview from your source."}</p>{(intelligence?.learningObjectives as string[] | null)?.length ? <div className="mt-6 border-t border-emerald-200/80 pt-5"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-emerald-800">You will be able to</p><ul className="mt-3 space-y-2">{(intelligence?.learningObjectives as string[]).slice(0, 3).map(objective => <li key={objective} className="flex gap-2 text-sm leading-6 text-emerald-950"><CheckCircle2 className="mt-1 h-3.5 w-3.5 shrink-0 text-emerald-700" />{objective}</li>)}</ul></div> : null}</article></section> : null}

    {tab === "read" ? <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Original source</p><h2 className="mt-2 font-display text-3xl tracking-[-.05em] text-slate-950">Read the material itself.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">The source is always available. ZhiyaAI never replaces it with a summary.</p></div>{units.isLoading ? <div className="mt-6 space-y-3">{[1, 2, 3].map(item => <div key={item} className="h-32 animate-pulse rounded-3xl bg-white" />)}</div> : <div className="mt-6 space-y-4">{units.data?.map(unit => <article key={unit.id} className="rounded-[1.6rem] border border-slate-200 bg-white p-6 shadow-[0_8px_25px_rgba(36,61,98,.04)]"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-sky-700">{unit.unitType} {unit.unitIndex}{unit.title ? ` · ${unit.title}` : ""}</p><p className="mt-4 whitespace-pre-wrap font-reading leading-8 text-slate-800">{unit.content}</p></article>)}</div>}</section> : null}

    {tab === "learn" ? <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-amber-700">Material intelligence</p><h2 className="mt-2 font-display text-3xl tracking-[-.05em] text-slate-950">Ideas worth bringing back.</h2><p className="mt-2 text-sm text-slate-600">Every definition is grounded in the uploaded source. Mastery changes only when you interact with it.</p></div>{concepts.length ? <Link href={lessonLink} className="inline-flex items-center gap-2 rounded-xl bg-amber-100 px-4 py-3 text-sm font-semibold text-amber-950 no-underline hover:bg-amber-200">Revise these ideas <ArrowRight className="h-4 w-4" /></Link> : null}</div>{concepts.length ? <div className="mt-6 grid gap-4 md:grid-cols-2">{concepts.map((concept, index) => <article key={concept.id} className="group rounded-[1.6rem] border border-slate-200 bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-[0_18px_45px_rgba(36,61,98,.08)]"><div className="flex items-start justify-between gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-amber-100 text-xs font-bold text-amber-800">{String(index + 1).padStart(2, "0")}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-slate-600">{masteryByConcept.get(concept.id) ?? "new"}</span></div><h3 className="mt-6 font-display text-2xl tracking-[-.04em] text-slate-950">{concept.canonicalName}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{concept.definition}</p><p className="mt-5 text-xs font-medium text-slate-400">From {(concept.evidence as { source?: { unitType?: string; unitIndex?: number } }[])?.[0]?.source?.unitType ?? "material"} {(concept.evidence as { source?: { unitIndex?: number } }[])?.[0]?.source?.unitIndex ?? ""}</p></article>)}</div> : <EmptyStudyState title="Ideas are taking shape.">ZhiyaAI waits for reliable source-backed concepts rather than filling this space with guesses.</EmptyStudyState>}</section> : null}

    {tab === "flashcards" ? <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-violet-700">Retrieval practice</p><h2 className="mt-2 font-display text-3xl tracking-[-.05em] text-slate-950">Bring ideas back from memory.</h2><p className="mt-2 text-sm text-slate-600">Cards remain attached to concepts ZhiyaAI found in this material.</p></div>{flashcards.data?.length ? <span className="text-sm text-slate-500">{Math.min(cardIndex + 1, flashcards.data.length)} of {flashcards.data.length}</span> : null}</div>{flashcards.isLoading ? <div className="mt-6 h-72 animate-pulse rounded-[1.8rem] bg-white" /> : !flashcards.data?.length ? <EmptyStudyState title="Create your first revision cards."><p>They will use only verified concepts from this material.</p><Button className="mt-5" disabled={studySet.isPending || !concepts.length} onClick={() => studySet.mutate({ materialId })}>Create grounded flashcards</Button></EmptyStudyState> : (() => { const card = flashcards.data[Math.min(cardIndex, flashcards.data.length - 1)]; return <div className="mt-6 max-w-2xl"><button type="button" onClick={() => setShowCardBack(value => !value)} className="min-h-72 w-full rounded-[1.8rem] border border-violet-200 bg-violet-50/70 p-8 text-left shadow-[0_18px_50px_rgba(109,79,180,.1)] transition hover:-translate-y-0.5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-violet-700">{showCardBack ? "Answer" : "Prompt"}</p><p className="mt-8 font-display text-3xl leading-tight tracking-[-.04em] text-slate-950">{showCardBack ? card.back : card.front}</p><p className="mt-10 text-xs text-violet-700/70">Tap to {showCardBack ? "return to prompt" : "reveal answer"} · Source evidence retained</p></button><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" className="bg-white" onClick={() => rateFlashcard.mutate({ materialId, flashcardId: card.id, rating: "again" })}>Again</Button><Button variant="outline" className="bg-white" onClick={() => rateFlashcard.mutate({ materialId, flashcardId: card.id, rating: "hard" })}>Hard</Button><Button onClick={() => rateFlashcard.mutate({ materialId, flashcardId: card.id, rating: "good" })}>Got it</Button></div></div>; })()}</section> : null}

    {tab === "quiz" ? <section className="mt-7"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-rose-700">Concept check</p><h2 className="mt-2 font-display text-3xl tracking-[-.05em] text-slate-950">Test the connections, not your memory of wording.</h2><p className="mt-2 text-sm text-slate-600">Each answer updates only the relevant concept’s learning signal.</p>{quiz.isLoading ? <div className="mt-6 h-72 animate-pulse rounded-[1.8rem] bg-white" /> : !quiz.data?.quiz ? <EmptyStudyState title="A short check is ready when you are."><p>ZhiyaAI will create a conceptual quiz from verified ideas in this material.</p><Button className="mt-5" disabled={studySet.isPending || !concepts.length} onClick={() => studySet.mutate({ materialId })}>Create conceptual quiz</Button></EmptyStudyState> : <div className="mt-6 space-y-5">{quiz.data.questions.map((question, index) => { const response = quizFeedback[question.id]; return <article key={question.id} className="rounded-[1.6rem] border border-slate-200 bg-white p-6 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-rose-700">Question {index + 1}</p><h3 className="mt-3 max-w-2xl font-display text-2xl tracking-[-.04em] text-slate-950">{question.prompt}</h3><div className="mt-6 grid gap-2">{(question.choices ?? []).map(choice => <Button key={choice} variant="outline" disabled={Boolean(response) || answerQuestion.isPending} className="h-auto justify-start whitespace-normal bg-white py-3.5 text-left leading-6 hover:border-rose-300 hover:bg-rose-50" onClick={() => answerQuestion.mutate({ questionId: question.id, selectedAnswer: choice })}>{choice}</Button>)}</div>{response ? <div className={`mt-5 rounded-2xl p-5 text-sm leading-6 ${response.isCorrect ? "bg-emerald-50 text-emerald-950" : "bg-rose-50 text-rose-950"}`}><p className="font-semibold">{response.isCorrect ? "Correct" : "Not quite"}</p><p className="mt-1">{response.explanation}</p><p className="mt-2 text-xs opacity-70">Explanation is grounded in this material.</p></div> : null}</article>; })}</div>}</section> : null}

    {tab === "notes" ? <section className="mt-7 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><aside><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-700">Your notebook</p><h2 className="mt-2 font-display text-3xl tracking-[-.05em] text-slate-950">Keep the thoughts worth returning to.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Notes remain with this material. Generated notes keep their evidence; your personal notes remain yours.</p><div className="mt-6 space-y-3">{notes.length ? notes.map(note => <article key={note.id} className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-medium text-slate-900">{note.title}</h3><p className="mt-1 line-clamp-3 text-sm leading-6 text-slate-600">{note.content}</p></article>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white/60 p-5 text-sm leading-6 text-slate-500">No saved notes yet. Add the thought you want your future self to find.</div>}</div></aside><div className="rounded-[1.8rem] border border-emerald-100 bg-emerald-50/60 p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-emerald-800">New personal note</p><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="What do you want to remember?" className="mt-5 bg-white" /><Textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Write your thought in your own words…" className="mt-3 min-h-52 bg-white" /><Button className="mt-4" disabled={saveNote.isPending || !title.trim() || !content.trim()} onClick={() => saveNote.mutate({ materialId, title: title.trim(), content: content.trim() })}>Save note</Button></div></section> : null}
  </div></AppShell>;
}
